spring.application.name=StrgSys

# Conexión a MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/almacen_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Configuración de logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.wcsono.strgSys=DEBUG

# Puerto del servidor (opcional)
# server.port=8081