spring.application.name=strgSys

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/almacen_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
logging.level.org.hibernate.type.descriptor.sql=TRACE


# Configuración de logging
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.wcsono.strgSys=DEBUG
# ? Este es tu paquete base, aquí se mostrarán tus logger.info/debug

# Puerto del servidor (descomenta si quieres cambiarlo)
# server.port=8081

