spring.application.name=StrgSys

# Conexión a MySQL local
spring.datasource.url=jdbc:mysql://localhost:3306/plasticosalmacen?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Ajuste de logging para Hibernate (evita saturación)
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=warn
logging.level.org.hibernate.type.descriptor.sql=warn

# Configuración de logging general
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.wcsono.strgSys=DEBUG

# Puerto del servidor (opcional)
# server.port=8081
# Tiempo de sesión en segundos (5 minutos = 300 segundos)
server.servlet.session.timeout=300
